apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-listings-image-cache
  namespace: ai-listings
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
