import type { AuthStep, PhotoShot } from '@/types/listings'

const STOP_WORDS = new Set([
  'the', 'a', 'an', 'of', 'for', 'and', 'or', 'to', 'on', 'in', 'with', 'is', 'are',
  'check', 'confirm', 'verify', 'that', 'this', 'any', 'note',
])

function keywords(text: string): Set<string> {
  return new Set(
    text
      .toLowerCase()
      .split(/[^a-z0-9]+/)
      .filter((word) => word.length > 2 && !STOP_WORDS.has(word)),
  )
}

function hasMatchingShot(authStep: AuthStep, photoPlan: PhotoShot[]): boolean {
  const authKeywords = keywords(`${authStep.step} ${authStep.guidance}`)
  if (authKeywords.size < 2) return false
  const requiredOverlap = Math.min(2, authKeywords.size)
  return photoPlan.some((shot) => {
    const shotKeywords = keywords(`${shot.shot} ${shot.description}`)
    let overlap = 0
    for (const word of authKeywords) {
      if (shotKeywords.has(word)) overlap += 1
    }
    return overlap >= requiredOverlap
  })
}

function buildShotForAuthStep(authStep: AuthStep, order: number): PhotoShot {
  return {
    shot: `${authStep.step} (authenticity check)`,
    description: `Close-up photo documenting: ${authStep.guidance}`,
    required: true,
    photo_type: 'auth_card',
    order,
  }
}

/**
 * Ensures every `auth_plan` item that requires a photo has a corresponding entry in
 * `photo_plan`. step2's photo_plan and step5's auth_plan are generated by two separate LLM
 * calls with no cross-reference, so coverage of authenticity-relevant shots in the studio
 * shot list is otherwise coincidental rather than guaranteed. Matching is a deterministic
 * keyword-overlap heuristic (no LLM call) so this stays cheap, fast, and testable.
 *
 * Appended auth_card shots are assigned order values continuing from the highest existing
 * order so they appear at the end of the shoot sequence.
 */
export function reconcilePhotoPlan(authPlan: AuthStep[], photoPlan: PhotoShot[]): PhotoShot[] {
  const result = [...photoPlan]
  let nextOrder = Math.max(0, ...photoPlan.map((s) => s.order ?? 0))
  for (const authStep of authPlan) {
    if (!authStep.photo_required) continue
    if (hasMatchingShot(authStep, result)) continue
    nextOrder += 1
    result.push(buildShotForAuthStep(authStep, nextOrder))
  }
  return result
}
